[package]
name = "rustforge"
version = "0.1.0"
authors = ["Scotow <contact@scotow.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rayon = "1.3.0"
num_cpus = "1.12.0"